### ISSUE TITLE
Discussion forum for slicklang

### ISSUE THREAD

**Issue by oubiwann** [ExaScience/slick#1]
Decide upon and set up a forum for Slick discussion.

**Comment by oubiwann** [comment]
@pcostanza Are you okay with Google Groups?

If so, I can save you some minutes and set that up ...

**Comment by pcostanza** [comment]
Yes, that would be great. Thanks a lot for volunteering...

**Comment by oubiwann** [comment]
Sure thing! List is created: slicklang@googlegroups.com

I demoted myself from owner to manager (feel free to demote me further!) and set the owners to the two email addresses used in your commits for the repo :-)
